Repository acm-ucr/tkd-website, pull requests merged in 2025-02, with the labels that each got.

#48 MR About Us Additional Info
  package-lock.json
  package.json
  src/app/about/page.tsx
  src/components/about/AdditionalInfo.tsx
Labels: ready for review

#68 Made navbar bigger
  src/components/Navbar.tsx
Labels: ready for review

#72 Event Landing
  public/events/event-landing.webp
  src/app/events/page.tsx
  src/components/events/Landing.tsx
  src/components/gallery/Landing.tsx
Labels: ready for review

#63 work
  src/components/Button.tsx
  src/components/home/SparringGear.tsx
Labels: requested changes

#71 MR for MemberSignUp
  src/components/Button.tsx
  src/components/home/Signup.tsx
Labels: ready for review, reviewed

#55 gmatt20/mr-home-landing-section and responsive drop down menu
  src/app/layout.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/components/home/Landing.tsx
  src/data/NavData.ts
Labels: requested changes

#80 add links
  src/components/Footer.tsx
Labels: ready for review

#82 gmatt20/mr-sparring-gear-comp
  src/components/Button.tsx
  src/components/Navbar.tsx
  src/components/home/SparringGear.tsx
Labels: ready for review

#69 MR 404 Page
  public/404page-background.webp
  public/taekwondo-404-background.webp
  src/app/not-found.tsx
Labels: ready for review, requested changes

#81 fixed
  src/components/home/Landing.tsx
Labels: requested changes

#87 About Landing
  src/components/about/Landing.tsx
Labels: ready for review, requested changes

#100 gmatt20/nav-x -overflow
  src/components/Navbar.tsx
  src/components/board/BoardMemberCard.tsx
  src/components/board/BoardMembers.tsx
  src/components/home/Landing.tsx
Labels: ready for review

#106 made my own tweaks to it but animation should be good
  package-lock.json
  package.json
  src/components/board/BoardMemberCard.tsx
Labels: requested changes

#102 Animated Home Landing Page
  src/components/home/Landing.tsx
Labels: ready for review, requested changes

#92 Added mobile responsiveness to Board Landing Component
  public/Board/boardGroupImage.webp
  public/Board/boardLanding.webp
  src/components/board/Landing.tsx
  src/data/BoardData.ts
Labels: requested changes

#111 mobile responsiveness for Events Landing
  src/components/events/Landing.tsx
Labels: ready for review

#91 Added info to sign up section
  src/components/Button.tsx
  src/components/home/Signup.tsx
Labels: ready for review

#93 MR - gallery - landing
  src/components/gallery/Landing.tsx
Labels: requested changes

#114 gmatt20/navbar-animation
  package-lock.json
  src/app/layout.tsx
  src/components/Navbar.tsx
Labels: ready for review
