Repository acm-ucr/tkd-website, pull requests merged in 2025-03, with the labels that each got.

#125 fixed overflow in boardpage
  src/components/board/Landing.tsx
Labels: ready for review

#129 scroll should work
  package-lock.json
  package.json
  src/components/events/Landing.tsx
Labels: ready for review

#134 Added sign up animations
  package-lock.json
  package.json
  src/app/not-found.tsx
  src/components/home/Signup.tsx
Labels: ready for review

#141 Haokun yang123/mr about landing
  src/components/about/Landing.tsx
Labels: ready for review

#149 Made code edits
  src/components/gallery/ImageCarousel.tsx
  src/components/gallery/Landing.tsx
  src/components/home/Signup.tsx
Labels: ready for review

#153 Haokun yang123/animation about us landing
  src/components/about/Landing.tsx
Labels: ready for review

#155 Daniyal/sparring animation fixed
  package-lock.json
  package.json
  src/components/home/SparringGear.tsx
Labels: ready for review, requested changes

#159 made quality code changes
  package-lock.json
  src/components/board/Landing.tsx
  src/components/home/Landing.tsx
Labels: ready for review

#161 Fixed home landing sliding animation causing overflow
  src/components/home/Landing.tsx
Labels: ready for review

#162 Added animation to gallery landing
  src/components/gallery/Landing.tsx
Labels: ready for review

#163 Veritasia/new calendar
  package-lock.json
  package.json
  src/app/events/page.tsx
  src/components/events/Calendar.tsx
  src/components/events/EventCard.tsx
  src/components/events/EventCol.tsx
  src/components/events/Landing.tsx
  src/components/events/button.tsx
  src/components/events/dialog.tsx
  src/lib/utils.ts
  src/types/calendar.ts
Labels: reviewed
