Repository acm-ucr/tkd-website, pull requests merged in 2025-01, with the labels that each got.

#20 Our Mission component in About Us page
  package-lock.json
  src/app/about/page.tsx
  src/components/about/Mission.tsx
Labels: ready for review, requested changes

#24 Created recurring button component
  src/components/Button.tsx
Labels: requested changes

#29 added changes
  src/components/events/EventCol.tsx
  src/components/events/MoreEvent.tsx
Labels: ready for review

#23 Created About Us Additional Information Section
  public/about/background.webp
  src/app/about/page.tsx
  src/components/about/AdditionalInfo.tsx
  src/components/about/AddtionalInfo.tsx
Labels: ready for review

#26 Haokun yang123/landing section
  public/landing/postcss.config.webp
  src/app/page.tsx
  src/components/home/Landing.tsx
Labels: ready for review

#22 Created the footer component
  package-lock.json
  package.json
  public/tkd-icon.webp
  src/app/page.tsx
  src/components/Footer.tsx
Labels: ready for review, requested changes

#46 Changed title and added favicon
  public/favicon.ico
  src/app/favicon.ico
  src/app/layout.tsx
Labels: ready for review

#44 404 PageNotFound page
  public/404page-background.webp
  src/app/not-found.tsx
  src/components/Button.tsx
Labels: ready for review, requested changes

#49 sparringgear (new branch)
  package-lock.json
  public/home/sparringGear.webp
  src/app/page.tsx
  src/components/home/SparringGear.tsx
Labels: requested changes

#51 Navbar
  public/logo.webp
  src/components/Navbar.tsx
  src/components/TKD navbar.png
Labels: ready for review, requested changes

#30 Board Landing Component
  package-lock.json
  package.json
  public/board/boardGroupImage.webp
  src/components/board/Landing.tsx
Labels: ready for review

#28 Andrewchen/gallerylanding
  public/gallery/landing-image.webp
  src/app/gallery/page.tsx
  src/components/Footer.tsx
  src/components/gallery/Landing.tsx
Labels: ready for review, requested changes

#50 member signup
  public/home/Signupemember.webp
  src/components/home/Signup.tsx
Labels: ready for review
